
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Components/Header";
import "./globals.css";
import Provider from "./Provider";
import TProvider from './Components/ThemeProvider';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TProvider>
      <Provider>
          <Header/>
          {children}
      </Provider>
      </TProvider>
        </body>
    </html>
  );
}
